In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 
warnings.filterwarnings('ignore')


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

#Import Models 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier , GradientBoostingClassifier
from sklearn.neighbors import  KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix

In [5]:
dataset = pd.read_csv('Training.csv')

In [7]:
dataset

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze                                prognosis  
0                     0                         Fungal infection  
1                     0                         Fungal infection  
2                     0                         Fungal infection  
3                     0                         Fungal infection  
4                     0                    

In [9]:
dataset.shape

(4920, 133)

In [11]:
dataset.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [13]:
dataset.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [15]:
dataset.head(2)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  

[2 rows x 133 columns]

In [17]:
dataset.prognosis.value_counts()

prognosis
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
All

In [19]:
len(dataset.prognosis.value_counts())

41

In [21]:
dataset.prognosis.unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [23]:
X = dataset.drop('prognosis' , axis = 1)
y = dataset['prognosis']

In [25]:
le = LabelEncoder()
le.fit(y)
Y = le.transform(y)

In [27]:
Y

array([15, 15, 15, ..., 38, 35, 27])

In [29]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [31]:
Y

array([15, 15, 15, ..., 38, 35, 27])

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X,Y , test_size=0.3, random_state=42)

In [35]:
X_train

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
682         0          0                     0                    0   
3963        0          0                     0                    0   
3126        0          0                     0                    0   
4480        0          0                     0                    0   
3411        0          0                     0                    0   
...       ...        ...                   ...                  ...   
4426        0          1                     0                    0   
466         0          0                     0                    0   
3092        0          1                     0                    0   
3772        1          1                     1                    0   
860         1          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
682           0       1           0             0        0                 0   
3963          0       1           0             0        0                 0   
3126          0       0           0             0        0                 0   
4480          0       0           0             0        1                 0   
3411          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4426          0       0           1             0        0                 0   
466           0       0           0             0        0                 0   
3092          0       1           1             0        0                 0   
3772          0       0           0             0        0                 0   
860           0       0           0             1        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
682   ...                   0           0         0             0   
3963  ...                   0           0         0             0   
3126  ...                   0           0         0             0   
4480  ...                   0           0         0             0   
3411  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4426  ...                   0           0         0             1   
466   ...                   0           0         0             0   
3092  ...                   0           0         0             0   
3772  ...                   0           0         0             0   
860   ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
682                     0                     0                   0        0   
3963                    0                     0                   0        0   
3126                    0                     0                   0        0   
4480                    0                     0                   0        0   
3411                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4426                    1                     1                   1        0   
466                     0                     0                   0        0   
3092                    0                     0                   0        0   
3772                    0                     0                   0        0   
860                     0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
682                      0                  0  
3963                     0                  0  
3126                     0                  0  
4480                     0                  0  
3411                     0                  0  
...                    ...                ...  
4426                     0                  0  
466               

In [37]:
X_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
373         0          1                     0                    0   
4916        0          1                     0                    0   
1550        0          0                     0                    0   
3081        0          0                     0                    0   
3857        1          0                     0                    0   
...       ...        ...                   ...                  ...   
3649        1          1                     1                    0   
1694        0          0                     0                    0   
4767        0          0                     0                    0   
3721        0          0                     0                    0   
2222        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
373           0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
1550          0       0           0             0        0                 0   
3081          0       0           0             0        0                 0   
3857          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
3649          0       0           0             0        0                 0   
1694          0       0           0             0        0                 0   
4767          0       0           0             0        1                 0   
3721          0       0           0             0        0                 0   
2222          0       1           1             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
373   ...                   0           1         1             0   
4916  ...                   1           1         1             0   
1550  ...                   0           0         0             0   
3081  ...                   0           0         0             0   
3857  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
3649  ...                   0           0         0             0   
1694  ...                   0           0         0             0   
4767  ...                   0           0         0             0   
3721  ...                   0           0         0             0   
2222  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
373                     0                     0                   0        0   
4916                    0                     0                   0        0   
1550                    0                     0                   0        0   
3081                    0                     0                   0        0   
3857                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
3649                    0                     0                   0        0   
1694                    0                     0                   0        0   
4767                    0                     0                   0        0   
3721                    0                     0                   0        0   
2222                    0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
373                      0                  0  
4916                     0                  0  
1550                     0                  0  
3081                     0                  0  
3857                     0                  0  
...                    ...                ...  
3649                     0                  0  
1694              

In [39]:
models = {
    'SVC': SVC(kernel = 'linear'), 
    'Random_forest' : RandomForestClassifier(n_estimators= 100 , random_state=42),
    'Gradiant_Boosting': GradientBoostingClassifier(n_estimators=100 , random_state = 42),
    'MultiNomialNB' : MultinomialNB(),
    'Kneighbours': KNeighborsClassifier(n_neighbors= 5 )
}


for model_name , model in models.items():
    model.fit(X_train,y_train)

    y_pred = model.predict(X_test)

    accuracy  = accuracy_score(y_test, y_pred )

    cm = confusion_matrix(y_test , y_pred)

    print('-=================================================================')
    print(f"{model_name } accuracy :{accuracy}")
    print(f"{model_name }  Confusion_matrics : {cm}")
    print(np.array2string(cm, separator = ",") )

-=================================================================
SVC accuracy :1.0
SVC  Confusion_matrics : [[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
[[32, 0, 0,..., 0, 0, 0],
 [ 0,39, 0,..., 0, 0, 0],
 [ 0, 0,41,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,36, 0, 0],
 [ 0, 0, 0,..., 0,37, 0],
 [ 0, 0, 0,..., 0, 0,39]]
-=================================================================
Random_forest accuracy :1.0
Random_forest  Confusion_matrics : [[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
[[32, 0, 0,..., 0, 0, 0],
 [ 0,39, 0,..., 0, 0, 0],
 [ 0, 0,41,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,36, 0, 0],
 [ 0, 0, 0,..., 0,37, 0],
 [ 0, 0, 0,..., 0, 0,39]]
-=================================================================
Gradiant_Boosting accuracy :1.0
Gradiant_Boosting  Confus

In [40]:
rf = RandomForestClassifier(n_estimators= 100 , random_state=42)
rf.fit(X_train , y_train)
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test , y_pred)
accuracy

1.0

In [41]:
svc = SVC(kernel = 'linear')
svc = SVC(kernel = 'linear')
svc.fit(X_train , y_train)
y_pred = svc.predict(X_test)
accuracy = accuracy_score(y_test , y_pred)
accuracy

1.0

In [65]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import pickle

# Load a sample dataset
data = load_iris()
X, y = data.data, data.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the models
rf_model = RandomForestClassifier()
svc_model = SVC()

# Train the models
rf_model.fit(X_train, y_train)
svc_model.fit(X_train, y_train)

# Save the models to files
with open('rf.pkl', 'wb') as file:
    pickle.dump(rf_model, file)

with open('svc.pkl', 'wb') as file:
    pickle.dump(svc_model, file)

In [67]:
import pickle 
pickle.dump(rf , open('svc.pkl','wb') ) 

 
pickle.dump(svc , open('svc.pkl','wb') )

In [69]:
with open('rf.pkl', 'wb') as file:
    pickle.dump(rf_model, file)

with open('svc.pkl', 'wb') as file:
    pickle.dump(svc_model, file)

In [71]:
rf = pickle.load(open('rf.pkl', 'rb'))
svc = pickle.load(open('svc.pkl', 'rb'))


In [73]:
rf

RandomForestClassifier()

In [77]:
import pandas as pd

# Convert numpy array to pandas DataFrame
X_test_df = pd.DataFrame(X_test, columns=data.feature_names)

# Now you can use .iloc
X_test_df.iloc[1].values.reshape(1, -1)

array([[5.7, 3.8, 1.7, 0.3]])

In [81]:
rf.predict([[0, 1, 0, 0]])

array([0])

In [85]:
svc.predict([[0, 1, 0, 0]])

array([0])

In [89]:
import pandas as pd

# Convert numpy array to pandas DataFrame
X_test_df = pd.DataFrame(X_test, columns=data.feature_names)

# Now you can use .iloc
X_test_df.iloc[7].values.reshape(1, -1)

array([[6.9, 3.1, 5.1, 2.3]])

In [93]:
import numpy as np

# Define the array using numpy
input_data = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
                      dtype=np.int64)

# Now you can use input_data in your prediction, for example:
# rf_model.predict(input_data)


In [97]:
print(rf.n_features_in_)


4


In [113]:

correct_input = [[0, 1, 2, 3]]  

# Make prediction with RandomForestClassifier
prediction = rf.predict(correct_input)
print(prediction)



[0]


In [115]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [117]:
precaution = pd.read_csv("precautions_df.csv")
workout = pd.read_csv("workout_df.csv")
medication = pd.read_csv('medications.csv')
diets = pd.read_csv('diets.csv')
description = pd.read_csv("description.csv")

In [119]:
def helper(dis):
    descr = description[description['Disease'] == dis ]['Description']
    descr = " ".join({ w for w in descr})
    
    pre = precaution[precaution['Disease'] == dis ][['Precaution_1',	'Precaution_2',	'Precaution_3'	,'Precaution_4']]
    pre  = [col for col in pre.values]


    die = diets[diets['Disease']== dis ]['Diet']
    die = [die for die in die.values]
    work = workout[workout['disease']== dis ]['workout']

    med = medication[medication['Disease'] == dis ]['Medication']
    med = [med for med in med.values]

    return descr , pre , die , med, work





symptom_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}

diseases_list = {15: 'Fungal infection', 20: 'Hepatitis C', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 21: 'Hepatitis D', 19: 'Hepatitis B', 4: 'Allergy', 40: 'hepatitis A', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 27: 'Impetigo'}




#model prediction 

def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptom_dict))
    for item in patient_symptoms:
        input_vector[symptom_dict[item]] = 1
    return diseases_list[svc.predict([input_vector])[0]]

In [145]:
print(symptom_dict.keys())
def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptom_dict))
    for item in patient_symptoms:
        # Use .lower() to handle case sensitivity
        item_cleaned = item.strip().lower()  # Normalize the input
        # Check if the cleaned symptom is in the symptom_dict
        if item_cleaned in symptom_dict:
            input_vector[symptom_dict[item_cleaned]] = 1
        else:
            print(f"Warning: '{item}' not found in symptom dictionary.")
    return diseases_list[svc.predict([input_vector])[0]]
symptom_dict = {
    'fungal infection': 0,  # Add your other symptoms here with unique indices
    # Other symptoms...
}
# Getting user input and processing it
symptoms = input("Enter Your Symptoms Here.. ")  # Example input
user_symptoms = [s.strip().lower() for s in symptoms.split(',')]


dict_keys(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_

Enter Your Symptoms Here..  itching
